### ISSUE TITLE
[Anaconda install Mac OSX] source activate

### ISSUE THREAD

**Issue by egvalentejr** [kialio/gsfcpyboot#5]
"source activate" by itself yields:
Error: no environment provided.

Anaconda Launcher app indicates I have on environment called root

"source activate root" instead works.

**Comment by kialio** [comment]
Ok.  Are you still having issues or is it working now?

**Comment by egvalentejr** [comment]
Oh yes it works I was just sharing this peculiarity of the Anaconda for Mac which didn't get captured in the instructions.  Thanks
